# Generated by Django 4.1.3 on 2022-11-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_zviera', models.AutoField(primary_key=True, serialize=False)),
                ('druh', models.CharField(max_length=255)),
                ('meno', models.CharField(max_length=255)),
                ('vek', models.PositiveIntegerField()),
                ('datum_registracie', models.DateField()),
                ('obrazok', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id_pecovatel', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_uzivatel', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('heslo', models.CharField(max_length=255)),
                ('aktivni', models.IntegerField()),
                ('zamestnanec_id', models.PositiveIntegerField(blank=True, null=True)),
                ('klient_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id_veterinar', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id_dobrovolnik', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
                ('doveryhodnost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id_vencenia', models.AutoField(primary_key=True, serialize=False)),
                ('venceny_od', models.DateField()),
                ('venceny_do', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VetRequest',
            fields=[
                ('id_poziadavky', models.AutoField(primary_key=True, serialize=False)),
                ('datum_vytvorenia', models.DateField()),
                ('obsah', models.CharField(max_length=255)),
                ('stav', models.CharField(max_length=255)),
                ('pecovatelid', models.ForeignKey(db_column='PecovatelID', on_delete=django.db.models.deletion.CASCADE, to='shelter.caregiver')),
                ('veterinarid', models.ForeignKey(db_column='VeterinarID', on_delete=django.db.models.deletion.CASCADE, to='shelter.vet')),
                ('zvieraid', models.ForeignKey(db_column='ZvieraID', on_delete=django.db.models.deletion.CASCADE, to='shelter.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_rezervacie', models.AutoField(primary_key=True, serialize=False)),
                ('datum_vytvorenia', models.DateField()),
                ('rezervovany_od', models.DateField()),
                ('rezervovany_do', models.DateField()),
                ('schvalenie', models.IntegerField(blank=True, null=True)),
                ('stav', models.CharField(blank=True, max_length=255, null=True)),
                ('dobrovolnikid', models.ForeignKey(db_column='DobrovolnikID', on_delete=django.db.models.deletion.CASCADE, to='shelter.volunteer')),
                ('zvieraid', models.ForeignKey(db_column='ZvieraID', on_delete=django.db.models.deletion.CASCADE, to='shelter.animal')),
            ],
        ),
    ]
