# Generated by Django 4.1.3 on 2022-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dobrovolnik',
            fields=[
                ('id_dobrovolnik', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
                ('doveryhodnost', models.IntegerField()),
            ],
            options={
                'db_table': 'Dobrovolnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pecovatel',
            fields=[
                ('id_pecovatel', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
            ],
            options={
                'db_table': 'Pecovatel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poziadavka',
            fields=[
                ('id_poziadavky', models.AutoField(primary_key=True, serialize=False)),
                ('datum_vytvorenia', models.DateField()),
                ('obsah', models.CharField(max_length=255)),
                ('stav', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Poziadavka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rezervacia',
            fields=[
                ('id_rezervacie', models.AutoField(primary_key=True, serialize=False)),
                ('datum_vytvorenia', models.DateField()),
                ('rezervovany_od', models.DateField()),
                ('rezervovany_do', models.DateField()),
                ('schvalenie', models.IntegerField()),
                ('stav', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Rezervacia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id_uzivatel', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(max_length=11)),
                ('email', models.CharField(db_collation='utf8mb4_unicode_520_ci', max_length=255, unique=True)),
                ('heslo', models.CharField(db_collation='utf8mb4_unicode_520_ci', max_length=255)),
                ('aktivni', models.IntegerField()),
                ('zamestnanec_id', models.PositiveIntegerField(blank=True, null=True)),
                ('klient_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Uzivatel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vencenie',
            fields=[
                ('id_vencenia', models.AutoField(primary_key=True, serialize=False)),
                ('venceny_od', models.DateField()),
                ('venceny_do', models.DateField()),
            ],
            options={
                'db_table': 'Vencenie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinar',
            fields=[
                ('id_veterinar', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
            ],
            options={
                'db_table': 'Veterinar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zviera',
            fields=[
                ('id_zviera', models.AutoField(primary_key=True, serialize=False)),
                ('druh', models.CharField(max_length=255)),
                ('meno', models.CharField(max_length=255)),
                ('vek', models.PositiveIntegerField()),
                ('datum_registracie', models.DateField()),
                ('obrazok', models.CharField(blank=True, db_collation='utf8mb4_unicode_520_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Zviera',
                'managed': False,
            },
        ),
    ]
