# Generated by Django 4.1.3 on 2022-11-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_zviera', models.AutoField(primary_key=True, serialize=False)),
                ('druh', models.CharField(max_length=255)),
                ('meno', models.CharField(max_length=255)),
                ('vek', models.PositiveIntegerField()),
                ('datum_registracie', models.DateField()),
                ('obrazok', models.CharField(blank=True, db_collation='utf8mb4_unicode_520_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Zviera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id_pecovatel', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
            ],
            options={
                'db_table': 'Pecovatel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_rezervacie', models.AutoField(primary_key=True, serialize=False)),
                ('datum_vytvorenia', models.DateField()),
                ('rezervovany_od', models.DateField()),
                ('rezervovany_do', models.DateField()),
                ('schvalenie', models.IntegerField(blank=True, null=True)),
                ('stav', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Rezervacia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_uzivatel', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(max_length=11)),
                ('email', models.CharField(db_collation='utf8mb4_unicode_520_ci', max_length=255, unique=True)),
                ('heslo', models.CharField(db_collation='utf8mb4_unicode_520_ci', max_length=255)),
                ('aktivni', models.IntegerField()),
                ('zamestnanec_id', models.PositiveIntegerField(blank=True, null=True)),
                ('klient_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Uzivatel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id_veterinar', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
            ],
            options={
                'db_table': 'Veterinar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VetRequest',
            fields=[
                ('id_poziadavky', models.AutoField(primary_key=True, serialize=False)),
                ('datum_vytvorenia', models.DateField()),
                ('obsah', models.CharField(max_length=255)),
                ('stav', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Poziadavka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id_dobrovolnik', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
                ('doveryhodnost', models.IntegerField()),
            ],
            options={
                'db_table': 'Dobrovolnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id_vencenia', models.AutoField(primary_key=True, serialize=False)),
                ('venceny_od', models.DateField()),
                ('venceny_do', models.DateField()),
            ],
            options={
                'db_table': 'Vencenie',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Dobrovolnik',
        ),
        migrations.DeleteModel(
            name='Pecovatel',
        ),
        migrations.DeleteModel(
            name='Poziadavka',
        ),
        migrations.DeleteModel(
            name='Rezervacia',
        ),
        migrations.DeleteModel(
            name='Uzivatel',
        ),
        migrations.DeleteModel(
            name='Vencenie',
        ),
        migrations.DeleteModel(
            name='Veterinar',
        ),
        migrations.DeleteModel(
            name='Zviera',
        ),
    ]
