# Generated by Django 4.1.3 on 2022-11-21 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelter', '0002_delete_user_alter_reservation_dobrovolnikid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetrequest',
            name='pecovatelid',
            field=models.ForeignKey(db_column='PecovatelID', on_delete=django.db.models.deletion.CASCADE, related_name='pecovatel_req', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='veterinarid',
            field=models.ForeignKey(db_column='VeterinarID', on_delete=django.db.models.deletion.CASCADE, related_name='vet_req', to=settings.AUTH_USER_MODEL),
        ),
    ]
