# Generated by Django 4.1.3 on 2022-11-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_alter_vetrequest_pecovatelid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='stav',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
