# Generated by Django 4.1.3 on 2022-11-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_alter_reservation_stav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='schvalenie',
            field=models.IntegerField(default=0),
        ),
    ]
