# Generated by Django 4.1.3 on 2022-11-22 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelter', '0005_alter_reservation_schvalenie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='datum_vytvorenia',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='id_rezervacie',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='rezervovany_do',
            new_name='reserved_from',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='rezervovany_od',
            new_name='reserved_to',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='stav',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='vetrequest',
            old_name='obsah',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='vetrequest',
            old_name='datum_vytvorenia',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='vetrequest',
            old_name='id_poziadavky',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vetrequest',
            old_name='stav',
            new_name='state',
        ),
        migrations.AddField(
            model_name='reservation',
            name='approval',
            field=models.IntegerField(db_column='approval', default=0),
        ),
    ]
