# Generated by Django 4.1.3 on 2022-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id_pecovatel', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('datum_narodenia', models.DateField()),
            ],
        ),
    ]
